name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/kivy/buildozer:latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'APK
        run: |
          yes | cp -n /home/user/.buildozer/android/platform/android-sdk 2>/dev/null || true
          buildozer -v android debug

      - name: Upload de l'APK
        uses: actions/upload-artifact@v4
        with:
          name: freeze-screen-apk
          path: bin/*.apk
