name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:latest
      options: --user root
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Build de l'APK
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          buildozer -v android debug

      - name: Upload de l'APK
        uses: actions/upload-artifact@v4
        with:
          name: freeze-screen-apk
          path: bin/*.apk
